version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: health-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: healthdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - health-network

  redis:
    image: redis:7-alpine
    container_name: health-redis
    ports:
      - "6379:6379"
    networks:
      - health-network
    
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: health-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - health-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: health-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - health-network

networks:
  health-network:
    driver: bridge

volumes:
  mysql-data: