server:
  port: 8082

spring:
  application:
    name: health-data-service
  datasource:
    url: jdbc:mysql://localhost:3306/healthdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  sql:
    init:
      mode: never

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      version: '@project.version@'

logging:
  level:
    com.healthdata.health: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"